# 作業 

In [2]:
import numpy as np

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

In [3]:
print(np.zeros((2, 3)))
print(np.empty((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [0. 0. 0.]]


np.zeros(): 建立元素全為 0的陣列

np.empty(): 在未初始化情況下，建立給定形狀的陣列，元素值會被隨機給定。

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [43]:
from numpy.random import default_rng
rng = default_rng()

a= rng.random((2,3))
a

array([[0.82587972, 0.41505476, 0.51034029],
       [0.99137079, 0.71234509, 0.19997757]])

In [44]:
a.round(0)

array([[1., 0., 1.],
       [1., 1., 0.]])

### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。


In [46]:
m = 20
n = 40
a = np.random.randint(m,n,size=(2,3))
a

array([[39, 36, 21],
       [33, 32, 39]])